# Generated by Django 3.2.8 on 2021-10-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='votes',
        ),
    ]
