# Generated by Django 3.2.8 on 2021-10-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_remove_vote_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='vote_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5),
        ),
    ]
