# Generated by Django 3.2.8 on 2021-10-25 15:09

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_vote_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='summary',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to=restaurants.models.content_file_name),
        ),
    ]
