# Generated by Django 3.2.8 on 2021-10-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20211025_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='published_date',
        ),
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
